### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by MFGSparka** [gpailler/Android2Wp_SMSConverter#1]
I know thats not the right place to post this but...

I tryed to run your fantatic script. I tryed it on Windows and i tryed it on ubuntu,debian, and so on.
The problem is, that the installationway you describet in the readme file is not working.

Can u give some more informations about your System, and other dependencies. 
Maybe you can install it as an webservice so we can use it per remote?

**Comment by gpailler** [comment]
Can you describe the error you have? If it's related to libxml2, you probably have to take a look on (http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu) 

About the webservice, I thinked about that. But are you confident to send all your SMS to an unknown service?

**Comment by MFGSparka** [comment]
Ok here are the steps i have done so fare on the windows 10 machine
- installed python 3.5.1
- added it to the PATH
- run cmd.exe as admin
- cloned the git repo
- generated the venv with python3 -m venv venv
- updated pip
- downloaded lxml als wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
- copied the file to the venv
- pip install lxml

and now I try to install the pycrypto. but there isnt a version for python3.5.1 so I tryed to installe an older version of pycryto. First it runs. But there is an error because the _AES.dll isn't there.

So i stucked. 

Now I'll try it again an an ubuntun virtual machine.

And your are right. All my messages to an unknown service isn't a good idea. But I think that there are a lot of people out there wich don't have the abilitys to run an python script ;-)

**Comment by gpailler** [comment]
I used python 3.4. Maybe you should try to downgrade to this version to retrieve dependencies.

**Comment by MFGSparka** [comment]
I now have tryed it on the windows machine with 3.4
the script crashes with:
`File: C:\Python34\lib\encodings\cp1252.px. line 23 in decode
return codecs.charmap_decode(input, self.errors.decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 6147: character maps to <undefined>`

with ubuntu it's a mess to install the modules and run them correctly

first I generatet a virtual environment with virtualenv -p python3.4 venv so that there is only python3
now I'm trying to install this ahhhh lxml. but everytime it fails with 
... /usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status 
error command 'x86_64-linux-gnu-gcc' fails width exit status 1

i keep trying :-(

**Comment by gpailler** [comment]
I found a way to use the script online
- Create an account on https://www.pythonanywhere.com/
- Start a new Bash console
- In the console, execute following command:

``` bash
git clone https://github.com/gpailler/Android2Wp_SMSConverter
```
- In PythonAnywhere management, select Files section and import XML and MSG files in Android2Wp_SMSConverter folder.
- In the console, execute following commands:

``` bash
cd Android2Wp_SMSConverter
python3.4 converter.py --xml android.xml --msg windowsphone.msg
```
- Finally, you can retrieve generated file

Can you try to use the script this way?

**Comment by MFGSparka** [comment]
Ohhhh yeah.!!!!
That worked very well.
Only the File up- and download was bit tricky because my files are round about 5MB.
Uploadet them as zip. Unpacked them with the bash.
And than the magic happened...
I only lost the emoticons but so what. I  have all my sms back. Had to remove them directliy in the original xml file.

Where is your donation button ?

**Comment by gpailler** [comment]
I'm glad it works fine ;-)

Donation button? I never think about that but if you're really happy with this tool, you can send me something using PayPal: https://www.paypal.me/gpailler ;-)

**Comment by gpailler** [comment]
I updated README to explain the https://www.pythonanywhere.com/ way and added a web conversion page
